/**
 * Canonical audit-log action names.
 */
export const AuditAction = {
  // Auth
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_REFRESH: 'AUTH_REFRESH',
  AUTH_PASSWORD_CHANGE: 'AUTH_PASSWORD_CHANGE',

  // School
  SCHOOL_CREATE: 'SCHOOL_CREATE',
  SCHOOL_UPDATE: 'SCHOOL_UPDATE',
  SCHOOL_DELETE: 'SCHOOL_DELETE',

  // Users
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',

  // Students
  STUDENT_CREATE: 'STUDENT_CREATE',
  STUDENT_UPDATE: 'STUDENT_UPDATE',
  STUDENT_DELETE: 'STUDENT_DELETE',

  // Teachers
  TEACHER_CREATE: 'TEACHER_CREATE',
  TEACHER_UPDATE: 'TEACHER_UPDATE',
  TEACHER_DELETE: 'TEACHER_DELETE',

  // Parents
  PARENT_CREATE: 'PARENT_CREATE',
  PARENT_UPDATE: 'PARENT_UPDATE',
  PARENT_DELETE: 'PARENT_DELETE',

  // Academics
  BRANCH_CREATE: 'BRANCH_CREATE',
  BRANCH_UPDATE: 'BRANCH_UPDATE',
  BRANCH_DELETE: 'BRANCH_DELETE',
  ACADEMIC_YEAR_CREATE: 'ACADEMIC_YEAR_CREATE',
  ACADEMIC_YEAR_UPDATE: 'ACADEMIC_YEAR_UPDATE',
  ACADEMIC_YEAR_DELETE: 'ACADEMIC_YEAR_DELETE',
  CLASS_CREATE: 'CLASS_CREATE',
  CLASS_UPDATE: 'CLASS_UPDATE',
  CLASS_DELETE: 'CLASS_DELETE',
  ENROLLMENT_CREATE: 'ENROLLMENT_CREATE',
  ENROLLMENT_UPDATE: 'ENROLLMENT_UPDATE',
  ENROLLMENT_DELETE: 'ENROLLMENT_DELETE',
  ATTENDANCE_CREATE: 'ATTENDANCE_CREATE',
  ATTENDANCE_UPDATE: 'ATTENDANCE_UPDATE',
  ASSIGNMENT_CREATE: 'ASSIGNMENT_CREATE',
  ASSIGNMENT_UPDATE: 'ASSIGNMENT_UPDATE',
  ASSIGNMENT_DELETE: 'ASSIGNMENT_DELETE',
  RESULT_CREATE: 'RESULT_CREATE',
  RESULT_UPDATE: 'RESULT_UPDATE',

  // RBAC
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  ROLE_PERMISSIONS_UPDATE: 'ROLE_PERMISSIONS_UPDATE',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];