/**
 * Centralized permission identifiers.
 *
 * Mirrors the seeded `Permission.name` values stored in the database.
 * Use with `@Permissions(...)` together with `PermissionsGuard`.
 */
export enum Permission {
  // School
  SCHOOL_READ = 'SCHOOL_READ',
  SCHOOL_CREATE = 'SCHOOL_CREATE',
  SCHOOL_UPDATE = 'SCHOOL_UPDATE',
  SCHOOL_DELETE = 'SCHOOL_DELETE',

  // Users
  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Students
  STUDENT_READ = 'STUDENT_READ',
  STUDENT_CREATE = 'STUDENT_CREATE',
  STUDENT_UPDATE = 'STUDENT_UPDATE',
  STUDENT_DELETE = 'STUDENT_DELETE',

  // Teachers
  TEACHER_READ = 'TEACHER_READ',
  TEACHER_CREATE = 'TEACHER_CREATE',
  TEACHER_UPDATE = 'TEACHER_UPDATE',
  TEACHER_DELETE = 'TEACHER_DELETE',

  // Parents
  PARENT_READ = 'PARENT_READ',
  PARENT_CREATE = 'PARENT_CREATE',
  PARENT_UPDATE = 'PARENT_UPDATE',
  PARENT_DELETE = 'PARENT_DELETE',

  // Classes
  CLASS_READ = 'CLASS_READ',
  CLASS_CREATE = 'CLASS_CREATE',
  CLASS_UPDATE = 'CLASS_UPDATE',
  CLASS_DELETE = 'CLASS_DELETE',

  // Attendance
  ATTENDANCE_READ = 'ATTENDANCE_READ',
  ATTENDANCE_CREATE = 'ATTENDANCE_CREATE',
  ATTENDANCE_UPDATE = 'ATTENDANCE_UPDATE',

  // Assignments
  ASSIGNMENT_READ = 'ASSIGNMENT_READ',
  ASSIGNMENT_CREATE = 'ASSIGNMENT_CREATE',
  ASSIGNMENT_UPDATE = 'ASSIGNMENT_UPDATE',
  ASSIGNMENT_DELETE = 'ASSIGNMENT_DELETE',

  // Exams
  EXAM_READ = 'EXAM_READ',
  EXAM_CREATE = 'EXAM_CREATE',
  EXAM_UPDATE = 'EXAM_UPDATE',
  EXAM_DELETE = 'EXAM_DELETE',

  // Results
  RESULT_READ = 'RESULT_READ',
  RESULT_CREATE = 'RESULT_CREATE',
  RESULT_UPDATE = 'RESULT_UPDATE',

  // Notifications
  NOTIFICATION_READ = 'NOTIFICATION_READ',
  NOTIFICATION_CREATE = 'NOTIFICATION_CREATE',

  // Audit logs
  AUDIT_LOG_READ = 'AUDIT_LOG_READ',
}

export const ALL_PERMISSIONS: Permission[] = Object.values(Permission);