export { api, API_BASE_URL, toApiError } from "./client";
export * from "./helpers";
export * from "./factory";

export { authApi } from "./auth";
export { usersApi } from "./users";
export { schoolsApi } from "./schools";
export { branchesApi } from "./branches";
export { academicYearsApi } from "./academic-years";
export { classesApi } from "./classes";
export { sectionsApi } from "./sections";
export { subjectsApi } from "./subjects";
export { coursesApi } from "./courses";
export { studentsApi } from "./students";
export { teachersApi } from "./teachers";
export { parentsApi } from "./parents";
export { enrollmentsApi } from "./enrollments";
export { attendanceApi } from "./attendance";
export { assignmentsApi } from "./assignments";
export { examsApi } from "./exams";
export { resultsApi } from "./results";
export { notificationsApi } from "./notifications";
export { auditLogsApi } from "./audit-logs";
export { superAdminApi } from "./super-admin";
export { schoolAdminApi } from "./school-admin";
export { rolesApi, permissionsApi } from "./roles";
export { filesApi } from "./files";